### ISSUE TITLE
Can't get the functions.length spec working

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-spec#5]
Here is the pull request: https://github.com/MrPowers/spark-spec/pull/4

The code in the spec is working when pasted in a Spark terminal shell, but not working in the spec file.  @abhisara and I are both confused about this.

**Comment by jasonsatran** [comment]
@MrPowers 

The expected DataFrame had two nullable columns.  I submitted a PR with an explicit schema and it appears to have resolved the issue.

**Comment by MrPowers** [comment]
Awesome work @jasonsatran - thanks!
