### ISSUE TITLE
Create DataFrames with a syntax that's more concise

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-spec#56]
The `spark.createDataFrame` syntax is used frequently in the project and is quite verbose.

I added a `spark.createDF` project that's more concise.  [This commit](https://github.com/MrPowers/spark-spec/commit/4e11afa6cede0df223b11fbb5dd8ae6420a4bd4e) shows an example of `createDF` in action.

@snithish @nathanlim45 @eclosson @xta - Let me know your thoughts on this new syntax.  Thanks!

**Comment by snithish** [comment]
@MrPowers `spark.createDF` does seem better, moving out the `parallelize` and `StructType` seems helpful. But it seems a bit off, that we are not using Spark 2 type safety features and instead rely on Dataframe which is essentially Dataset[Row], which won't let us to do something like this refer to #57 
```
case class Person(name: String, age: Int)
val sourceDF = Seq(Person("Alice", 20), Person("Bob", 16)).toDS
sourceDF.filter(x => x.age > 18) 
```

**Comment by MrPowers** [comment]
Thanks @snithish.  Yea, `createDF` is for creating DataFrames and I agree that I can't be used to create a Dataset.

It looks like it's easier to create Datasets... not sure if we'll need a helper method when creating Datasets.

You're right that we should shift more specs to use Datasets in this project.  Most of the specs use DataFrames.

**Comment by MrPowers** [comment]
@snithish - I replace `createDataFrame` with `createDF` in [the ColumnSpec file](https://github.com/MrPowers/spark-spec/commit/8e81666b419f8fda6c44d7529a9b52267683956e).  Let me know what you think.

Do you think we should add DataFrame and Dataset examples for each method?  I'd like to start playing around with the Dataset API more.

**Comment by snithish** [comment]
@MrPowers `createDF ` looks clean and concise, Yes I believe we should be adding a dataframe and a dataset example if possible. I will work on a function to compare dataset without having to do explicit conversion to dataframe.

**Comment by MrPowers** [comment]
@snithish - Thanks for the feedback.  I added a Dataset#alias example in [this commit](https://github.com/MrPowers/spark-spec/commit/0310ef57915cfdd14f914e8f85008d7a40480169).  I agree that we should add specs that use the Dataset and DataFrame APIs.

Thanks again for your awesome feedback!
