### ISSUE TITLE
Codacy Integration

### ISSUE THREAD

**Issue by snithish** [MrPowers/spark-spec#61]
Any thoughts on integrating codacy for static code analysis, I feel it will help in code reviews, thoughts?

**Comment by MrPowers** [comment]
Sounds like a great idea.  I'll add it now 😄

**Comment by MrPowers** [comment]
@snithish - I added the badge in [this commit](https://github.com/MrPowers/spark-spec/commit/44d47c68f52f4170a219fc9c28b576a0799094c3).  Take a look at the README and let me know if it looks good.

I didn't know about Codacy - thanks for encouraging me to take a look!!!

**Comment by snithish** [comment]
@MrPowers looks good.
